[package]
name = "rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
blstrs_plus = { version = "0.8.18" }
rug = { version = "1.28.0", features = ["serde"] }
serde = "1.0.219"
tarpc = "0.36.0"
tokio = "1.47.1"
