[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.99"
blake2 = "0.10.6"
rand = "0.9.2"
rand_chacha = "0.9.0"
rayon = "1.11.0"
rug = "1.28.0"
